export const batchPlannerAbi = [
  {
    type: "function",
    name: "batchVestingPlans",
    inputs: [
      { name: "locker", type: "address", internalType: "address" },
      { name: "token", type: "address", internalType: "address" },
      { name: "totalAmount", type: "uint256", internalType: "uint256" },
      {
        name: "plans",
        type: "tuple[]",
        internalType: "struct IBatchPlanner.Plan[]",
        components: [
          { name: "recipient", type: "address", internalType: "address" },
          { name: "amount", type: "uint256", internalType: "uint256" },
          { name: "start", type: "uint256", internalType: "uint256" },
          { name: "cliff", type: "uint256", internalType: "uint256" },
          { name: "rate", type: "uint256", internalType: "uint256" },
        ],
      },
      { name: "period", type: "uint256", internalType: "uint256" },
      { name: "vestingAdmin", type: "address", internalType: "address" },
      { name: "adminTransferOBO", type: "bool", internalType: "bool" },
      { name: "mintType", type: "uint8", internalType: "uint8" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
] as const;

export const kpkGovernorAbi = [
  { type: "constructor", inputs: [], stateMutability: "nonpayable" },
  { type: "receive", stateMutability: "payable" },
  {
    type: "function",
    name: "BALLOT_TYPEHASH",
    inputs: [],
    outputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "CLOCK_MODE",
    inputs: [],
    outputs: [{ name: "", type: "string", internalType: "string" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "COUNTING_MODE",
    inputs: [],
    outputs: [{ name: "", type: "string", internalType: "string" }],
    stateMutability: "pure",
  },
  {
    type: "function",
    name: "EXTENDED_BALLOT_TYPEHASH",
    inputs: [],
    outputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "cancel",
    inputs: [
      { name: "targets", type: "address[]", internalType: "address[]" },
      { name: "values", type: "uint256[]", internalType: "uint256[]" },
      { name: "calldatas", type: "bytes[]", internalType: "bytes[]" },
      { name: "descriptionHash", type: "bytes32", internalType: "bytes32" },
    ],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "castVote",
    inputs: [
      { name: "proposalId", type: "uint256", internalType: "uint256" },
      { name: "support", type: "uint8", internalType: "uint8" },
    ],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "castVoteBySig",
    inputs: [
      { name: "proposalId", type: "uint256", internalType: "uint256" },
      { name: "support", type: "uint8", internalType: "uint8" },
      { name: "voter", type: "address", internalType: "address" },
      { name: "signature", type: "bytes", internalType: "bytes" },
    ],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "castVoteWithReason",
    inputs: [
      { name: "proposalId", type: "uint256", internalType: "uint256" },
      { name: "support", type: "uint8", internalType: "uint8" },
      { name: "reason", type: "string", internalType: "string" },
    ],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "castVoteWithReasonAndParams",
    inputs: [
      { name: "proposalId", type: "uint256", internalType: "uint256" },
      { name: "support", type: "uint8", internalType: "uint8" },
      { name: "reason", type: "string", internalType: "string" },
      { name: "params", type: "bytes", internalType: "bytes" },
    ],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "castVoteWithReasonAndParamsBySig",
    inputs: [
      { name: "proposalId", type: "uint256", internalType: "uint256" },
      { name: "support", type: "uint8", internalType: "uint8" },
      { name: "voter", type: "address", internalType: "address" },
      { name: "reason", type: "string", internalType: "string" },
      { name: "params", type: "bytes", internalType: "bytes" },
      { name: "signature", type: "bytes", internalType: "bytes" },
    ],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "clock",
    inputs: [],
    outputs: [{ name: "", type: "uint48", internalType: "uint48" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "eip712Domain",
    inputs: [],
    outputs: [
      { name: "fields", type: "bytes1", internalType: "bytes1" },
      { name: "name", type: "string", internalType: "string" },
      { name: "version", type: "string", internalType: "string" },
      { name: "chainId", type: "uint256", internalType: "uint256" },
      { name: "verifyingContract", type: "address", internalType: "address" },
      { name: "salt", type: "bytes32", internalType: "bytes32" },
      { name: "extensions", type: "uint256[]", internalType: "uint256[]" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "execute",
    inputs: [
      { name: "targets", type: "address[]", internalType: "address[]" },
      { name: "values", type: "uint256[]", internalType: "uint256[]" },
      { name: "calldatas", type: "bytes[]", internalType: "bytes[]" },
      { name: "descriptionHash", type: "bytes32", internalType: "bytes32" },
    ],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "getVotes",
    inputs: [
      { name: "account", type: "address", internalType: "address" },
      { name: "timepoint", type: "uint256", internalType: "uint256" },
    ],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getVotesWithParams",
    inputs: [
      { name: "account", type: "address", internalType: "address" },
      { name: "timepoint", type: "uint256", internalType: "uint256" },
      { name: "params", type: "bytes", internalType: "bytes" },
    ],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "hasVoted",
    inputs: [
      { name: "proposalId", type: "uint256", internalType: "uint256" },
      { name: "account", type: "address", internalType: "address" },
    ],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "hashProposal",
    inputs: [
      { name: "targets", type: "address[]", internalType: "address[]" },
      { name: "values", type: "uint256[]", internalType: "uint256[]" },
      { name: "calldatas", type: "bytes[]", internalType: "bytes[]" },
      { name: "descriptionHash", type: "bytes32", internalType: "bytes32" },
    ],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "pure",
  },
  {
    type: "function",
    name: "initialize",
    inputs: [
      { name: "_token", type: "address", internalType: "contract IVotes" },
      {
        name: "_timelock",
        type: "address",
        internalType: "contract TimelockControllerUpgradeable",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "name",
    inputs: [],
    outputs: [{ name: "", type: "string", internalType: "string" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "nonces",
    inputs: [{ name: "owner", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "onERC1155BatchReceived",
    inputs: [
      { name: "", type: "address", internalType: "address" },
      { name: "", type: "address", internalType: "address" },
      { name: "", type: "uint256[]", internalType: "uint256[]" },
      { name: "", type: "uint256[]", internalType: "uint256[]" },
      { name: "", type: "bytes", internalType: "bytes" },
    ],
    outputs: [{ name: "", type: "bytes4", internalType: "bytes4" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "onERC1155Received",
    inputs: [
      { name: "", type: "address", internalType: "address" },
      { name: "", type: "address", internalType: "address" },
      { name: "", type: "uint256", internalType: "uint256" },
      { name: "", type: "uint256", internalType: "uint256" },
      { name: "", type: "bytes", internalType: "bytes" },
    ],
    outputs: [{ name: "", type: "bytes4", internalType: "bytes4" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "onERC721Received",
    inputs: [
      { name: "", type: "address", internalType: "address" },
      { name: "", type: "address", internalType: "address" },
      { name: "", type: "uint256", internalType: "uint256" },
      { name: "", type: "bytes", internalType: "bytes" },
    ],
    outputs: [{ name: "", type: "bytes4", internalType: "bytes4" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "proposalDeadline",
    inputs: [{ name: "proposalId", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "proposalEta",
    inputs: [{ name: "proposalId", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "proposalNeedsQueuing",
    inputs: [{ name: "proposalId", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "proposalProposer",
    inputs: [{ name: "proposalId", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "proposalSnapshot",
    inputs: [{ name: "proposalId", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "proposalThreshold",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "proposalVotes",
    inputs: [{ name: "proposalId", type: "uint256", internalType: "uint256" }],
    outputs: [
      { name: "againstVotes", type: "uint256", internalType: "uint256" },
      { name: "forVotes", type: "uint256", internalType: "uint256" },
      { name: "abstainVotes", type: "uint256", internalType: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "propose",
    inputs: [
      { name: "targets", type: "address[]", internalType: "address[]" },
      { name: "values", type: "uint256[]", internalType: "uint256[]" },
      { name: "calldatas", type: "bytes[]", internalType: "bytes[]" },
      { name: "description", type: "string", internalType: "string" },
    ],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "queue",
    inputs: [
      { name: "targets", type: "address[]", internalType: "address[]" },
      { name: "values", type: "uint256[]", internalType: "uint256[]" },
      { name: "calldatas", type: "bytes[]", internalType: "bytes[]" },
      { name: "descriptionHash", type: "bytes32", internalType: "bytes32" },
    ],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "quorum",
    inputs: [{ name: "blockNumber", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "quorumDenominator",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "quorumNumerator",
    inputs: [{ name: "timepoint", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "quorumNumerator",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "relay",
    inputs: [
      { name: "target", type: "address", internalType: "address" },
      { name: "value", type: "uint256", internalType: "uint256" },
      { name: "data", type: "bytes", internalType: "bytes" },
    ],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "setProposalThreshold",
    inputs: [
      {
        name: "newProposalThreshold",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setVotingDelay",
    inputs: [
      { name: "newVotingDelay", type: "uint48", internalType: "uint48" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setVotingPeriod",
    inputs: [
      { name: "newVotingPeriod", type: "uint32", internalType: "uint32" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "state",
    inputs: [{ name: "proposalId", type: "uint256", internalType: "uint256" }],
    outputs: [
      { name: "", type: "uint8", internalType: "enum IGovernor.ProposalState" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "supportsInterface",
    inputs: [{ name: "interfaceId", type: "bytes4", internalType: "bytes4" }],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "timelock",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "token",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "contract IERC5805" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "updateQuorumNumerator",
    inputs: [
      { name: "newQuorumNumerator", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "updateTimelock",
    inputs: [
      {
        name: "newTimelock",
        type: "address",
        internalType: "contract TimelockControllerUpgradeable",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "version",
    inputs: [],
    outputs: [{ name: "", type: "string", internalType: "string" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "votingDelay",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "votingPeriod",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  { type: "event", name: "EIP712DomainChanged", inputs: [], anonymous: false },
  {
    type: "event",
    name: "Initialized",
    inputs: [
      {
        name: "version",
        type: "uint64",
        indexed: false,
        internalType: "uint64",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ProposalCanceled",
    inputs: [
      {
        name: "proposalId",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ProposalCreated",
    inputs: [
      {
        name: "proposalId",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "proposer",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "targets",
        type: "address[]",
        indexed: false,
        internalType: "address[]",
      },
      {
        name: "values",
        type: "uint256[]",
        indexed: false,
        internalType: "uint256[]",
      },
      {
        name: "signatures",
        type: "string[]",
        indexed: false,
        internalType: "string[]",
      },
      {
        name: "calldatas",
        type: "bytes[]",
        indexed: false,
        internalType: "bytes[]",
      },
      {
        name: "voteStart",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "voteEnd",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "description",
        type: "string",
        indexed: false,
        internalType: "string",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ProposalExecuted",
    inputs: [
      {
        name: "proposalId",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ProposalQueued",
    inputs: [
      {
        name: "proposalId",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "etaSeconds",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ProposalThresholdSet",
    inputs: [
      {
        name: "oldProposalThreshold",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "newProposalThreshold",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "QuorumNumeratorUpdated",
    inputs: [
      {
        name: "oldQuorumNumerator",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "newQuorumNumerator",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "TimelockChange",
    inputs: [
      {
        name: "oldTimelock",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "newTimelock",
        type: "address",
        indexed: false,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "VoteCast",
    inputs: [
      {
        name: "voter",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "proposalId",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      { name: "support", type: "uint8", indexed: false, internalType: "uint8" },
      {
        name: "weight",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "reason",
        type: "string",
        indexed: false,
        internalType: "string",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "VoteCastWithParams",
    inputs: [
      {
        name: "voter",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "proposalId",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      { name: "support", type: "uint8", indexed: false, internalType: "uint8" },
      {
        name: "weight",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "reason",
        type: "string",
        indexed: false,
        internalType: "string",
      },
      { name: "params", type: "bytes", indexed: false, internalType: "bytes" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "VotingDelaySet",
    inputs: [
      {
        name: "oldVotingDelay",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "newVotingDelay",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "VotingPeriodSet",
    inputs: [
      {
        name: "oldVotingPeriod",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "newVotingPeriod",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  { type: "error", name: "CheckpointUnorderedInsertion", inputs: [] },
  { type: "error", name: "FailedInnerCall", inputs: [] },
  {
    type: "error",
    name: "GovernorAlreadyCastVote",
    inputs: [{ name: "voter", type: "address", internalType: "address" }],
  },
  {
    type: "error",
    name: "GovernorAlreadyQueuedProposal",
    inputs: [{ name: "proposalId", type: "uint256", internalType: "uint256" }],
  },
  { type: "error", name: "GovernorDisabledDeposit", inputs: [] },
  {
    type: "error",
    name: "GovernorInsufficientProposerVotes",
    inputs: [
      { name: "proposer", type: "address", internalType: "address" },
      { name: "votes", type: "uint256", internalType: "uint256" },
      { name: "threshold", type: "uint256", internalType: "uint256" },
    ],
  },
  {
    type: "error",
    name: "GovernorInvalidProposalLength",
    inputs: [
      { name: "targets", type: "uint256", internalType: "uint256" },
      { name: "calldatas", type: "uint256", internalType: "uint256" },
      { name: "values", type: "uint256", internalType: "uint256" },
    ],
  },
  {
    type: "error",
    name: "GovernorInvalidQuorumFraction",
    inputs: [
      { name: "quorumNumerator", type: "uint256", internalType: "uint256" },
      { name: "quorumDenominator", type: "uint256", internalType: "uint256" },
    ],
  },
  {
    type: "error",
    name: "GovernorInvalidSignature",
    inputs: [{ name: "voter", type: "address", internalType: "address" }],
  },
  { type: "error", name: "GovernorInvalidVoteType", inputs: [] },
  {
    type: "error",
    name: "GovernorInvalidVotingPeriod",
    inputs: [
      { name: "votingPeriod", type: "uint256", internalType: "uint256" },
    ],
  },
  {
    type: "error",
    name: "GovernorNonexistentProposal",
    inputs: [{ name: "proposalId", type: "uint256", internalType: "uint256" }],
  },
  {
    type: "error",
    name: "GovernorNotQueuedProposal",
    inputs: [{ name: "proposalId", type: "uint256", internalType: "uint256" }],
  },
  {
    type: "error",
    name: "GovernorOnlyExecutor",
    inputs: [{ name: "account", type: "address", internalType: "address" }],
  },
  {
    type: "error",
    name: "GovernorOnlyProposer",
    inputs: [{ name: "account", type: "address", internalType: "address" }],
  },
  { type: "error", name: "GovernorQueueNotImplemented", inputs: [] },
  {
    type: "error",
    name: "GovernorRestrictedProposer",
    inputs: [{ name: "proposer", type: "address", internalType: "address" }],
  },
  {
    type: "error",
    name: "GovernorUnexpectedProposalState",
    inputs: [
      { name: "proposalId", type: "uint256", internalType: "uint256" },
      {
        name: "current",
        type: "uint8",
        internalType: "enum IGovernor.ProposalState",
      },
      { name: "expectedStates", type: "bytes32", internalType: "bytes32" },
    ],
  },
  {
    type: "error",
    name: "InvalidAccountNonce",
    inputs: [
      { name: "account", type: "address", internalType: "address" },
      { name: "currentNonce", type: "uint256", internalType: "uint256" },
    ],
  },
  { type: "error", name: "InvalidInitialization", inputs: [] },
  { type: "error", name: "NotInitializing", inputs: [] },
  { type: "error", name: "QueueEmpty", inputs: [] },
  { type: "error", name: "QueueFull", inputs: [] },
  {
    type: "error",
    name: "SafeCastOverflowedUintDowncast",
    inputs: [
      { name: "bits", type: "uint8", internalType: "uint8" },
      { name: "value", type: "uint256", internalType: "uint256" },
    ],
  },
] as const;

export const proxyAdminAbi = [{
  "type": "constructor",
  "inputs": [{
    "name": "initialOwner",
    "type": "address",
    "internalType": "address",
  }],
  "stateMutability": "nonpayable",
}, {
  "type": "function",
  "name": "UPGRADE_INTERFACE_VERSION",
  "inputs": [],
  "outputs": [{ "name": "", "type": "string", "internalType": "string" }],
  "stateMutability": "view",
}, {
  "type": "function",
  "name": "owner",
  "inputs": [],
  "outputs": [{ "name": "", "type": "address", "internalType": "address" }],
  "stateMutability": "view",
}, {
  "type": "function",
  "name": "renounceOwnership",
  "inputs": [],
  "outputs": [],
  "stateMutability": "nonpayable",
}, {
  "type": "function",
  "name": "transferOwnership",
  "inputs": [{
    "name": "newOwner",
    "type": "address",
    "internalType": "address",
  }],
  "outputs": [],
  "stateMutability": "nonpayable",
}, {
  "type": "function",
  "name": "upgradeAndCall",
  "inputs": [
    {
      "name": "proxy",
      "type": "address",
      "internalType": "contract ITransparentUpgradeableProxy",
    },
    { "name": "implementation", "type": "address", "internalType": "address" },
    { "name": "data", "type": "bytes", "internalType": "bytes" },
  ],
  "outputs": [],
  "stateMutability": "payable",
}, {
  "type": "event",
  "name": "OwnershipTransferred",
  "inputs": [{
    "name": "previousOwner",
    "type": "address",
    "indexed": true,
    "internalType": "address",
  }, {
    "name": "newOwner",
    "type": "address",
    "indexed": true,
    "internalType": "address",
  }],
  "anonymous": false,
}, {
  "type": "error",
  "name": "OwnableInvalidOwner",
  "inputs": [{ "name": "owner", "type": "address", "internalType": "address" }],
}, {
  "type": "error",
  "name": "OwnableUnauthorizedAccount",
  "inputs": [{
    "name": "account",
    "type": "address",
    "internalType": "address",
  }],
}] as const;

export const transparentUpgradeableProxyAbi = [
  {
    "type": "constructor",
    "inputs": [
      { "name": "_logic", "type": "address", "internalType": "address" },
      { "name": "initialOwner", "type": "address", "internalType": "address" },
      { "name": "_data", "type": "bytes", "internalType": "bytes" },
    ],
    "stateMutability": "payable",
  },
  { "type": "fallback", "stateMutability": "payable" },
  {
    "type": "event",
    "name": "AdminChanged",
    "inputs": [{
      "name": "previousAdmin",
      "type": "address",
      "indexed": false,
      "internalType": "address",
    }, {
      "name": "newAdmin",
      "type": "address",
      "indexed": false,
      "internalType": "address",
    }],
    "anonymous": false,
  },
  {
    "type": "event",
    "name": "Upgraded",
    "inputs": [{
      "name": "implementation",
      "type": "address",
      "indexed": true,
      "internalType": "address",
    }],
    "anonymous": false,
  },
  {
    "type": "error",
    "name": "AddressEmptyCode",
    "inputs": [{
      "name": "target",
      "type": "address",
      "internalType": "address",
    }],
  },
  {
    "type": "error",
    "name": "ERC1967InvalidAdmin",
    "inputs": [{
      "name": "admin",
      "type": "address",
      "internalType": "address",
    }],
  },
  {
    "type": "error",
    "name": "ERC1967InvalidImplementation",
    "inputs": [{
      "name": "implementation",
      "type": "address",
      "internalType": "address",
    }],
  },
  { "type": "error", "name": "ERC1967NonPayable", "inputs": [] },
  { "type": "error", "name": "FailedInnerCall", "inputs": [] },
  { "type": "error", "name": "ProxyDeniedAdminAccess", "inputs": [] },
] as const;

export const kpkTokenAbi = [
  { "type": "constructor", "inputs": [], "stateMutability": "nonpayable" },
  {
    "type": "function",
    "name": "CLOCK_MODE",
    "inputs": [],
    "outputs": [{ "name": "", "type": "string", "internalType": "string" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "DOMAIN_SEPARATOR",
    "inputs": [],
    "outputs": [{ "name": "", "type": "bytes32", "internalType": "bytes32" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "allowance",
    "inputs": [{
      "name": "owner",
      "type": "address",
      "internalType": "address",
    }, { "name": "spender", "type": "address", "internalType": "address" }],
    "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "approve",
    "inputs": [{
      "name": "spender",
      "type": "address",
      "internalType": "address",
    }, { "name": "value", "type": "uint256", "internalType": "uint256" }],
    "outputs": [{ "name": "", "type": "bool", "internalType": "bool" }],
    "stateMutability": "nonpayable",
  },
  {
    "type": "function",
    "name": "balanceOf",
    "inputs": [{
      "name": "account",
      "type": "address",
      "internalType": "address",
    }],
    "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "burn",
    "inputs": [{
      "name": "value",
      "type": "uint256",
      "internalType": "uint256",
    }],
    "outputs": [],
    "stateMutability": "nonpayable",
  },
  {
    "type": "function",
    "name": "burnFrom",
    "inputs": [{
      "name": "account",
      "type": "address",
      "internalType": "address",
    }, { "name": "value", "type": "uint256", "internalType": "uint256" }],
    "outputs": [],
    "stateMutability": "nonpayable",
  },
  {
    "type": "function",
    "name": "checkpoints",
    "inputs": [{
      "name": "account",
      "type": "address",
      "internalType": "address",
    }, { "name": "pos", "type": "uint32", "internalType": "uint32" }],
    "outputs": [{
      "name": "",
      "type": "tuple",
      "internalType": "struct Checkpoints.Checkpoint208",
      "components": [{
        "name": "_key",
        "type": "uint48",
        "internalType": "uint48",
      }, { "name": "_value", "type": "uint208", "internalType": "uint208" }],
    }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "clock",
    "inputs": [],
    "outputs": [{ "name": "", "type": "uint48", "internalType": "uint48" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "decimals",
    "inputs": [],
    "outputs": [{ "name": "", "type": "uint8", "internalType": "uint8" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "decreaseTransferAllowance",
    "inputs": [
      { "name": "sender", "type": "address", "internalType": "address" },
      { "name": "recipient", "type": "address", "internalType": "address" },
      {
        "name": "subtractedValue",
        "type": "uint256",
        "internalType": "uint256",
      },
    ],
    "outputs": [{ "name": "success", "type": "bool", "internalType": "bool" }],
    "stateMutability": "nonpayable",
  },
  {
    "type": "function",
    "name": "delegate",
    "inputs": [{
      "name": "delegatee",
      "type": "address",
      "internalType": "address",
    }],
    "outputs": [],
    "stateMutability": "nonpayable",
  },
  {
    "type": "function",
    "name": "delegateBySig",
    "inputs": [
      { "name": "delegatee", "type": "address", "internalType": "address" },
      { "name": "nonce", "type": "uint256", "internalType": "uint256" },
      { "name": "expiry", "type": "uint256", "internalType": "uint256" },
      { "name": "v", "type": "uint8", "internalType": "uint8" },
      { "name": "r", "type": "bytes32", "internalType": "bytes32" },
      { "name": "s", "type": "bytes32", "internalType": "bytes32" },
    ],
    "outputs": [],
    "stateMutability": "nonpayable",
  },
  {
    "type": "function",
    "name": "delegates",
    "inputs": [{
      "name": "account",
      "type": "address",
      "internalType": "address",
    }],
    "outputs": [{ "name": "", "type": "address", "internalType": "address" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "eip712Domain",
    "inputs": [],
    "outputs": [
      { "name": "fields", "type": "bytes1", "internalType": "bytes1" },
      { "name": "name", "type": "string", "internalType": "string" },
      { "name": "version", "type": "string", "internalType": "string" },
      { "name": "chainId", "type": "uint256", "internalType": "uint256" },
      {
        "name": "verifyingContract",
        "type": "address",
        "internalType": "address",
      },
      { "name": "salt", "type": "bytes32", "internalType": "bytes32" },
      {
        "name": "extensions",
        "type": "uint256[]",
        "internalType": "uint256[]",
      },
    ],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "getPastTotalSupply",
    "inputs": [{
      "name": "timepoint",
      "type": "uint256",
      "internalType": "uint256",
    }],
    "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "getPastVotes",
    "inputs": [{
      "name": "account",
      "type": "address",
      "internalType": "address",
    }, { "name": "timepoint", "type": "uint256", "internalType": "uint256" }],
    "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "getVotes",
    "inputs": [{
      "name": "account",
      "type": "address",
      "internalType": "address",
    }],
    "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "increaseTransferAllowance",
    "inputs": [
      { "name": "sender", "type": "address", "internalType": "address" },
      { "name": "recipient", "type": "address", "internalType": "address" },
      { "name": "addedValue", "type": "uint256", "internalType": "uint256" },
    ],
    "outputs": [{ "name": "success", "type": "bool", "internalType": "bool" }],
    "stateMutability": "nonpayable",
  },
  {
    "type": "function",
    "name": "initialize",
    "inputs": [{
      "name": "initialOwner",
      "type": "address",
      "internalType": "address",
    }],
    "outputs": [],
    "stateMutability": "nonpayable",
  },
  {
    "type": "function",
    "name": "mint",
    "inputs": [{ "name": "to", "type": "address", "internalType": "address" }, {
      "name": "amount",
      "type": "uint256",
      "internalType": "uint256",
    }],
    "outputs": [],
    "stateMutability": "nonpayable",
  },
  {
    "type": "function",
    "name": "name",
    "inputs": [],
    "outputs": [{ "name": "", "type": "string", "internalType": "string" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "nonces",
    "inputs": [{
      "name": "owner",
      "type": "address",
      "internalType": "address",
    }],
    "outputs": [{
      "name": "nonce",
      "type": "uint256",
      "internalType": "uint256",
    }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "numCheckpoints",
    "inputs": [{
      "name": "account",
      "type": "address",
      "internalType": "address",
    }],
    "outputs": [{ "name": "", "type": "uint32", "internalType": "uint32" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "owner",
    "inputs": [],
    "outputs": [{ "name": "", "type": "address", "internalType": "address" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "paused",
    "inputs": [],
    "outputs": [{ "name": "", "type": "bool", "internalType": "bool" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "permit",
    "inputs": [
      { "name": "owner", "type": "address", "internalType": "address" },
      { "name": "spender", "type": "address", "internalType": "address" },
      { "name": "value", "type": "uint256", "internalType": "uint256" },
      { "name": "deadline", "type": "uint256", "internalType": "uint256" },
      { "name": "v", "type": "uint8", "internalType": "uint8" },
      { "name": "r", "type": "bytes32", "internalType": "bytes32" },
      { "name": "s", "type": "bytes32", "internalType": "bytes32" },
    ],
    "outputs": [],
    "stateMutability": "nonpayable",
  },
  {
    "type": "function",
    "name": "renounceOwnership",
    "inputs": [],
    "outputs": [],
    "stateMutability": "nonpayable",
  },
  {
    "type": "function",
    "name": "rescueToken",
    "inputs": [
      { "name": "token", "type": "address", "internalType": "contract IERC20" },
      { "name": "recipient", "type": "address", "internalType": "address" },
      { "name": "value", "type": "uint256", "internalType": "uint256" },
    ],
    "outputs": [{ "name": "success", "type": "bool", "internalType": "bool" }],
    "stateMutability": "nonpayable",
  },
  {
    "type": "function",
    "name": "symbol",
    "inputs": [],
    "outputs": [{ "name": "", "type": "string", "internalType": "string" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "totalSupply",
    "inputs": [],
    "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "transfer",
    "inputs": [{ "name": "to", "type": "address", "internalType": "address" }, {
      "name": "value",
      "type": "uint256",
      "internalType": "uint256",
    }],
    "outputs": [{ "name": "", "type": "bool", "internalType": "bool" }],
    "stateMutability": "nonpayable",
  },
  {
    "type": "function",
    "name": "transferAllowance",
    "inputs": [{
      "name": "sender",
      "type": "address",
      "internalType": "address",
    }, { "name": "recipient", "type": "address", "internalType": "address" }],
    "outputs": [{
      "name": "value",
      "type": "uint256",
      "internalType": "uint256",
    }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "transferAllowlist",
    "inputs": [{
      "name": "sender",
      "type": "address",
      "internalType": "address",
    }, { "name": "allowlisted", "type": "bool", "internalType": "bool" }],
    "outputs": [],
    "stateMutability": "nonpayable",
  },
  {
    "type": "function",
    "name": "transferAllowlisted",
    "inputs": [{
      "name": "sender",
      "type": "address",
      "internalType": "address",
    }],
    "outputs": [{
      "name": "allowlisted",
      "type": "bool",
      "internalType": "bool",
    }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "transferFrom",
    "inputs": [
      { "name": "from", "type": "address", "internalType": "address" },
      { "name": "to", "type": "address", "internalType": "address" },
      { "name": "value", "type": "uint256", "internalType": "uint256" },
    ],
    "outputs": [{ "name": "", "type": "bool", "internalType": "bool" }],
    "stateMutability": "nonpayable",
  },
  {
    "type": "function",
    "name": "transferOwnership",
    "inputs": [{
      "name": "newOwner",
      "type": "address",
      "internalType": "address",
    }],
    "outputs": [],
    "stateMutability": "nonpayable",
  },
  {
    "type": "function",
    "name": "unpause",
    "inputs": [],
    "outputs": [],
    "stateMutability": "nonpayable",
  },
  {
    "type": "event",
    "name": "Approval",
    "inputs": [{
      "name": "owner",
      "type": "address",
      "indexed": true,
      "internalType": "address",
    }, {
      "name": "spender",
      "type": "address",
      "indexed": true,
      "internalType": "address",
    }, {
      "name": "value",
      "type": "uint256",
      "indexed": false,
      "internalType": "uint256",
    }],
    "anonymous": false,
  },
  {
    "type": "event",
    "name": "DelegateChanged",
    "inputs": [{
      "name": "delegator",
      "type": "address",
      "indexed": true,
      "internalType": "address",
    }, {
      "name": "fromDelegate",
      "type": "address",
      "indexed": true,
      "internalType": "address",
    }, {
      "name": "toDelegate",
      "type": "address",
      "indexed": true,
      "internalType": "address",
    }],
    "anonymous": false,
  },
  {
    "type": "event",
    "name": "DelegateVotesChanged",
    "inputs": [{
      "name": "delegate",
      "type": "address",
      "indexed": true,
      "internalType": "address",
    }, {
      "name": "previousVotes",
      "type": "uint256",
      "indexed": false,
      "internalType": "uint256",
    }, {
      "name": "newVotes",
      "type": "uint256",
      "indexed": false,
      "internalType": "uint256",
    }],
    "anonymous": false,
  },
  {
    "type": "event",
    "name": "EIP712DomainChanged",
    "inputs": [],
    "anonymous": false,
  },
  {
    "type": "event",
    "name": "Initialized",
    "inputs": [{
      "name": "version",
      "type": "uint64",
      "indexed": false,
      "internalType": "uint64",
    }],
    "anonymous": false,
  },
  {
    "type": "event",
    "name": "OwnershipTransferred",
    "inputs": [{
      "name": "previousOwner",
      "type": "address",
      "indexed": true,
      "internalType": "address",
    }, {
      "name": "newOwner",
      "type": "address",
      "indexed": true,
      "internalType": "address",
    }],
    "anonymous": false,
  },
  {
    "type": "event",
    "name": "Paused",
    "inputs": [{
      "name": "account",
      "type": "address",
      "indexed": false,
      "internalType": "address",
    }],
    "anonymous": false,
  },
  {
    "type": "event",
    "name": "Transfer",
    "inputs": [{
      "name": "from",
      "type": "address",
      "indexed": true,
      "internalType": "address",
    }, {
      "name": "to",
      "type": "address",
      "indexed": true,
      "internalType": "address",
    }, {
      "name": "value",
      "type": "uint256",
      "indexed": false,
      "internalType": "uint256",
    }],
    "anonymous": false,
  },
  {
    "type": "event",
    "name": "TransferAllowlisting",
    "inputs": [{
      "name": "sender",
      "type": "address",
      "indexed": true,
      "internalType": "address",
    }, {
      "name": "allowlisted",
      "type": "bool",
      "indexed": true,
      "internalType": "bool",
    }],
    "anonymous": false,
  },
  {
    "type": "event",
    "name": "TransferApproval",
    "inputs": [{
      "name": "sender",
      "type": "address",
      "indexed": true,
      "internalType": "address",
    }, {
      "name": "recipient",
      "type": "address",
      "indexed": true,
      "internalType": "address",
    }, {
      "name": "value",
      "type": "uint256",
      "indexed": false,
      "internalType": "uint256",
    }],
    "anonymous": false,
  },
  {
    "type": "event",
    "name": "Unpaused",
    "inputs": [{
      "name": "account",
      "type": "address",
      "indexed": false,
      "internalType": "address",
    }],
    "anonymous": false,
  },
  {
    "type": "error",
    "name": "AddressEmptyCode",
    "inputs": [{
      "name": "target",
      "type": "address",
      "internalType": "address",
    }],
  },
  {
    "type": "error",
    "name": "AddressInsufficientBalance",
    "inputs": [{
      "name": "account",
      "type": "address",
      "internalType": "address",
    }],
  },
  { "type": "error", "name": "CheckpointUnorderedInsertion", "inputs": [] },
  { "type": "error", "name": "ECDSAInvalidSignature", "inputs": [] },
  {
    "type": "error",
    "name": "ECDSAInvalidSignatureLength",
    "inputs": [{
      "name": "length",
      "type": "uint256",
      "internalType": "uint256",
    }],
  },
  {
    "type": "error",
    "name": "ECDSAInvalidSignatureS",
    "inputs": [{ "name": "s", "type": "bytes32", "internalType": "bytes32" }],
  },
  {
    "type": "error",
    "name": "ERC20ExceededSafeSupply",
    "inputs": [{
      "name": "increasedSupply",
      "type": "uint256",
      "internalType": "uint256",
    }, { "name": "cap", "type": "uint256", "internalType": "uint256" }],
  },
  {
    "type": "error",
    "name": "ERC20InsufficientAllowance",
    "inputs": [
      { "name": "spender", "type": "address", "internalType": "address" },
      { "name": "allowance", "type": "uint256", "internalType": "uint256" },
      { "name": "needed", "type": "uint256", "internalType": "uint256" },
    ],
  },
  {
    "type": "error",
    "name": "ERC20InsufficientBalance",
    "inputs": [
      { "name": "sender", "type": "address", "internalType": "address" },
      { "name": "balance", "type": "uint256", "internalType": "uint256" },
      { "name": "needed", "type": "uint256", "internalType": "uint256" },
    ],
  },
  {
    "type": "error",
    "name": "ERC20InvalidApprover",
    "inputs": [{
      "name": "approver",
      "type": "address",
      "internalType": "address",
    }],
  },
  {
    "type": "error",
    "name": "ERC20InvalidReceiver",
    "inputs": [{
      "name": "receiver",
      "type": "address",
      "internalType": "address",
    }],
  },
  {
    "type": "error",
    "name": "ERC20InvalidSender",
    "inputs": [{
      "name": "sender",
      "type": "address",
      "internalType": "address",
    }],
  },
  {
    "type": "error",
    "name": "ERC20InvalidSpender",
    "inputs": [{
      "name": "spender",
      "type": "address",
      "internalType": "address",
    }],
  },
  {
    "type": "error",
    "name": "ERC2612ExpiredSignature",
    "inputs": [{
      "name": "deadline",
      "type": "uint256",
      "internalType": "uint256",
    }],
  },
  {
    "type": "error",
    "name": "ERC2612InvalidSigner",
    "inputs": [{
      "name": "signer",
      "type": "address",
      "internalType": "address",
    }, { "name": "owner", "type": "address", "internalType": "address" }],
  },
  {
    "type": "error",
    "name": "ERC5805FutureLookup",
    "inputs": [{
      "name": "timepoint",
      "type": "uint256",
      "internalType": "uint256",
    }, { "name": "clock", "type": "uint48", "internalType": "uint48" }],
  },
  { "type": "error", "name": "ERC6372InconsistentClock", "inputs": [] },
  { "type": "error", "name": "EnforcedPause", "inputs": [] },
  { "type": "error", "name": "ExpectedPause", "inputs": [] },
  { "type": "error", "name": "FailedInnerCall", "inputs": [] },
  {
    "type": "error",
    "name": "InsufficientBalanceToRescue",
    "inputs": [
      { "name": "token", "type": "address", "internalType": "contract IERC20" },
      { "name": "balance", "type": "uint256", "internalType": "uint256" },
      { "name": "value", "type": "uint256", "internalType": "uint256" },
    ],
  },
  {
    "type": "error",
    "name": "InsufficientTransferAllowance",
    "inputs": [
      { "name": "sender", "type": "address", "internalType": "address" },
      { "name": "recipient", "type": "address", "internalType": "address" },
      {
        "name": "_currentTransferAllowance",
        "type": "uint256",
        "internalType": "uint256",
      },
      { "name": "needed", "type": "uint256", "internalType": "uint256" },
    ],
  },
  {
    "type": "error",
    "name": "InvalidAccountNonce",
    "inputs": [{
      "name": "account",
      "type": "address",
      "internalType": "address",
    }, {
      "name": "currentNonce",
      "type": "uint256",
      "internalType": "uint256",
    }],
  },
  { "type": "error", "name": "InvalidInitialization", "inputs": [] },
  {
    "type": "error",
    "name": "InvalidTransferAllowlisting",
    "inputs": [{
      "name": "sender",
      "type": "address",
      "internalType": "address",
    }],
  },
  {
    "type": "error",
    "name": "InvalidTransferApproval",
    "inputs": [{
      "name": "sender",
      "type": "address",
      "internalType": "address",
    }],
  },
  { "type": "error", "name": "NotInitializing", "inputs": [] },
  {
    "type": "error",
    "name": "OwnableInvalidOwner",
    "inputs": [{
      "name": "owner",
      "type": "address",
      "internalType": "address",
    }],
  },
  {
    "type": "error",
    "name": "OwnableUnauthorizedAccount",
    "inputs": [{
      "name": "account",
      "type": "address",
      "internalType": "address",
    }],
  },
  {
    "type": "error",
    "name": "SafeCastOverflowedUintDowncast",
    "inputs": [{ "name": "bits", "type": "uint8", "internalType": "uint8" }, {
      "name": "value",
      "type": "uint256",
      "internalType": "uint256",
    }],
  },
  {
    "type": "error",
    "name": "SafeERC20FailedOperation",
    "inputs": [{
      "name": "token",
      "type": "address",
      "internalType": "address",
    }],
  },
  { "type": "error", "name": "TransferAllowlistingWhenUnpaused", "inputs": [] },
  { "type": "error", "name": "TransferApprovalWhenUnpaused", "inputs": [] },
  { "type": "error", "name": "TransferToTokenContract", "inputs": [] },
  {
    "type": "error",
    "name": "VotesExpiredSignature",
    "inputs": [{
      "name": "expiry",
      "type": "uint256",
      "internalType": "uint256",
    }],
  },
] as const;

export const timelockControllerAbi = [
  {
    "type": "constructor",
    "inputs": [
      { "name": "minDelay", "type": "uint256", "internalType": "uint256" },
      {
        "name": "proposers",
        "type": "address[]",
        "internalType": "address[]",
      },
      {
        "name": "executors",
        "type": "address[]",
        "internalType": "address[]",
      },
      { "name": "admin", "type": "address", "internalType": "address" },
    ],
    "stateMutability": "nonpayable",
  },
  { "type": "receive", "stateMutability": "payable" },
  {
    "type": "function",
    "name": "CANCELLER_ROLE",
    "inputs": [],
    "outputs": [{ "name": "", "type": "bytes32", "internalType": "bytes32" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "DEFAULT_ADMIN_ROLE",
    "inputs": [],
    "outputs": [{ "name": "", "type": "bytes32", "internalType": "bytes32" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "EXECUTOR_ROLE",
    "inputs": [],
    "outputs": [{ "name": "", "type": "bytes32", "internalType": "bytes32" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "PROPOSER_ROLE",
    "inputs": [],
    "outputs": [{ "name": "", "type": "bytes32", "internalType": "bytes32" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "cancel",
    "inputs": [
      { "name": "id", "type": "bytes32", "internalType": "bytes32" },
    ],
    "outputs": [],
    "stateMutability": "nonpayable",
  },
  {
    "type": "function",
    "name": "execute",
    "inputs": [
      { "name": "target", "type": "address", "internalType": "address" },
      { "name": "value", "type": "uint256", "internalType": "uint256" },
      { "name": "payload", "type": "bytes", "internalType": "bytes" },
      { "name": "predecessor", "type": "bytes32", "internalType": "bytes32" },
      { "name": "salt", "type": "bytes32", "internalType": "bytes32" },
    ],
    "outputs": [],
    "stateMutability": "payable",
  },
  {
    "type": "function",
    "name": "executeBatch",
    "inputs": [
      { "name": "targets", "type": "address[]", "internalType": "address[]" },
      { "name": "values", "type": "uint256[]", "internalType": "uint256[]" },
      { "name": "payloads", "type": "bytes[]", "internalType": "bytes[]" },
      { "name": "predecessor", "type": "bytes32", "internalType": "bytes32" },
      { "name": "salt", "type": "bytes32", "internalType": "bytes32" },
    ],
    "outputs": [],
    "stateMutability": "payable",
  },
  {
    "type": "function",
    "name": "getMinDelay",
    "inputs": [],
    "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "getOperationState",
    "inputs": [
      { "name": "id", "type": "bytes32", "internalType": "bytes32" },
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint8",
        "internalType": "enum TimelockController.OperationState",
      },
    ],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "getRoleAdmin",
    "inputs": [
      { "name": "role", "type": "bytes32", "internalType": "bytes32" },
    ],
    "outputs": [{ "name": "", "type": "bytes32", "internalType": "bytes32" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "getTimestamp",
    "inputs": [
      { "name": "id", "type": "bytes32", "internalType": "bytes32" },
    ],
    "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "grantRole",
    "inputs": [
      { "name": "role", "type": "bytes32", "internalType": "bytes32" },
      { "name": "account", "type": "address", "internalType": "address" },
    ],
    "outputs": [],
    "stateMutability": "nonpayable",
  },
  {
    "type": "function",
    "name": "hasRole",
    "inputs": [
      { "name": "role", "type": "bytes32", "internalType": "bytes32" },
      { "name": "account", "type": "address", "internalType": "address" },
    ],
    "outputs": [{ "name": "", "type": "bool", "internalType": "bool" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "hashOperation",
    "inputs": [
      { "name": "target", "type": "address", "internalType": "address" },
      { "name": "value", "type": "uint256", "internalType": "uint256" },
      { "name": "data", "type": "bytes", "internalType": "bytes" },
      { "name": "predecessor", "type": "bytes32", "internalType": "bytes32" },
      { "name": "salt", "type": "bytes32", "internalType": "bytes32" },
    ],
    "outputs": [{ "name": "", "type": "bytes32", "internalType": "bytes32" }],
    "stateMutability": "pure",
  },
  {
    "type": "function",
    "name": "hashOperationBatch",
    "inputs": [
      { "name": "targets", "type": "address[]", "internalType": "address[]" },
      { "name": "values", "type": "uint256[]", "internalType": "uint256[]" },
      { "name": "payloads", "type": "bytes[]", "internalType": "bytes[]" },
      { "name": "predecessor", "type": "bytes32", "internalType": "bytes32" },
      { "name": "salt", "type": "bytes32", "internalType": "bytes32" },
    ],
    "outputs": [{ "name": "", "type": "bytes32", "internalType": "bytes32" }],
    "stateMutability": "pure",
  },
  {
    "type": "function",
    "name": "isOperation",
    "inputs": [
      { "name": "id", "type": "bytes32", "internalType": "bytes32" },
    ],
    "outputs": [{ "name": "", "type": "bool", "internalType": "bool" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "isOperationDone",
    "inputs": [
      { "name": "id", "type": "bytes32", "internalType": "bytes32" },
    ],
    "outputs": [{ "name": "", "type": "bool", "internalType": "bool" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "isOperationPending",
    "inputs": [
      { "name": "id", "type": "bytes32", "internalType": "bytes32" },
    ],
    "outputs": [{ "name": "", "type": "bool", "internalType": "bool" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "isOperationReady",
    "inputs": [
      { "name": "id", "type": "bytes32", "internalType": "bytes32" },
    ],
    "outputs": [{ "name": "", "type": "bool", "internalType": "bool" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "onERC1155BatchReceived",
    "inputs": [
      { "name": "", "type": "address", "internalType": "address" },
      { "name": "", "type": "address", "internalType": "address" },
      { "name": "", "type": "uint256[]", "internalType": "uint256[]" },
      { "name": "", "type": "uint256[]", "internalType": "uint256[]" },
      { "name": "", "type": "bytes", "internalType": "bytes" },
    ],
    "outputs": [{ "name": "", "type": "bytes4", "internalType": "bytes4" }],
    "stateMutability": "nonpayable",
  },
  {
    "type": "function",
    "name": "onERC1155Received",
    "inputs": [
      { "name": "", "type": "address", "internalType": "address" },
      { "name": "", "type": "address", "internalType": "address" },
      { "name": "", "type": "uint256", "internalType": "uint256" },
      { "name": "", "type": "uint256", "internalType": "uint256" },
      { "name": "", "type": "bytes", "internalType": "bytes" },
    ],
    "outputs": [{ "name": "", "type": "bytes4", "internalType": "bytes4" }],
    "stateMutability": "nonpayable",
  },
  {
    "type": "function",
    "name": "onERC721Received",
    "inputs": [
      { "name": "", "type": "address", "internalType": "address" },
      { "name": "", "type": "address", "internalType": "address" },
      { "name": "", "type": "uint256", "internalType": "uint256" },
      { "name": "", "type": "bytes", "internalType": "bytes" },
    ],
    "outputs": [{ "name": "", "type": "bytes4", "internalType": "bytes4" }],
    "stateMutability": "nonpayable",
  },
  {
    "type": "function",
    "name": "renounceRole",
    "inputs": [
      { "name": "role", "type": "bytes32", "internalType": "bytes32" },
      {
        "name": "callerConfirmation",
        "type": "address",
        "internalType": "address",
      },
    ],
    "outputs": [],
    "stateMutability": "nonpayable",
  },
  {
    "type": "function",
    "name": "revokeRole",
    "inputs": [
      { "name": "role", "type": "bytes32", "internalType": "bytes32" },
      { "name": "account", "type": "address", "internalType": "address" },
    ],
    "outputs": [],
    "stateMutability": "nonpayable",
  },
  {
    "type": "function",
    "name": "schedule",
    "inputs": [
      { "name": "target", "type": "address", "internalType": "address" },
      { "name": "value", "type": "uint256", "internalType": "uint256" },
      { "name": "data", "type": "bytes", "internalType": "bytes" },
      { "name": "predecessor", "type": "bytes32", "internalType": "bytes32" },
      { "name": "salt", "type": "bytes32", "internalType": "bytes32" },
      { "name": "delay", "type": "uint256", "internalType": "uint256" },
    ],
    "outputs": [],
    "stateMutability": "nonpayable",
  },
  {
    "type": "function",
    "name": "scheduleBatch",
    "inputs": [
      { "name": "targets", "type": "address[]", "internalType": "address[]" },
      { "name": "values", "type": "uint256[]", "internalType": "uint256[]" },
      { "name": "payloads", "type": "bytes[]", "internalType": "bytes[]" },
      { "name": "predecessor", "type": "bytes32", "internalType": "bytes32" },
      { "name": "salt", "type": "bytes32", "internalType": "bytes32" },
      { "name": "delay", "type": "uint256", "internalType": "uint256" },
    ],
    "outputs": [],
    "stateMutability": "nonpayable",
  },
  {
    "type": "function",
    "name": "supportsInterface",
    "inputs": [
      { "name": "interfaceId", "type": "bytes4", "internalType": "bytes4" },
    ],
    "outputs": [{ "name": "", "type": "bool", "internalType": "bool" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "updateDelay",
    "inputs": [
      { "name": "newDelay", "type": "uint256", "internalType": "uint256" },
    ],
    "outputs": [],
    "stateMutability": "nonpayable",
  },
  {
    "type": "event",
    "name": "CallExecuted",
    "inputs": [
      {
        "name": "id",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32",
      },
      {
        "name": "index",
        "type": "uint256",
        "indexed": true,
        "internalType": "uint256",
      },
      {
        "name": "target",
        "type": "address",
        "indexed": false,
        "internalType": "address",
      },
      {
        "name": "value",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256",
      },
      {
        "name": "data",
        "type": "bytes",
        "indexed": false,
        "internalType": "bytes",
      },
    ],
    "anonymous": false,
  },
  {
    "type": "event",
    "name": "CallSalt",
    "inputs": [
      {
        "name": "id",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32",
      },
      {
        "name": "salt",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32",
      },
    ],
    "anonymous": false,
  },
  {
    "type": "event",
    "name": "CallScheduled",
    "inputs": [
      {
        "name": "id",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32",
      },
      {
        "name": "index",
        "type": "uint256",
        "indexed": true,
        "internalType": "uint256",
      },
      {
        "name": "target",
        "type": "address",
        "indexed": false,
        "internalType": "address",
      },
      {
        "name": "value",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256",
      },
      {
        "name": "data",
        "type": "bytes",
        "indexed": false,
        "internalType": "bytes",
      },
      {
        "name": "predecessor",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32",
      },
      {
        "name": "delay",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256",
      },
    ],
    "anonymous": false,
  },
  {
    "type": "event",
    "name": "Cancelled",
    "inputs": [
      {
        "name": "id",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32",
      },
    ],
    "anonymous": false,
  },
  {
    "type": "event",
    "name": "MinDelayChange",
    "inputs": [
      {
        "name": "oldDuration",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256",
      },
      {
        "name": "newDuration",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256",
      },
    ],
    "anonymous": false,
  },
  {
    "type": "event",
    "name": "RoleAdminChanged",
    "inputs": [
      {
        "name": "role",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32",
      },
      {
        "name": "previousAdminRole",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32",
      },
      {
        "name": "newAdminRole",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32",
      },
    ],
    "anonymous": false,
  },
  {
    "type": "event",
    "name": "RoleGranted",
    "inputs": [
      {
        "name": "role",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32",
      },
      {
        "name": "account",
        "type": "address",
        "indexed": true,
        "internalType": "address",
      },
      {
        "name": "sender",
        "type": "address",
        "indexed": true,
        "internalType": "address",
      },
    ],
    "anonymous": false,
  },
  {
    "type": "event",
    "name": "RoleRevoked",
    "inputs": [
      {
        "name": "role",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32",
      },
      {
        "name": "account",
        "type": "address",
        "indexed": true,
        "internalType": "address",
      },
      {
        "name": "sender",
        "type": "address",
        "indexed": true,
        "internalType": "address",
      },
    ],
    "anonymous": false,
  },
  { "type": "error", "name": "AccessControlBadConfirmation", "inputs": [] },
  {
    "type": "error",
    "name": "AccessControlUnauthorizedAccount",
    "inputs": [
      { "name": "account", "type": "address", "internalType": "address" },
      { "name": "neededRole", "type": "bytes32", "internalType": "bytes32" },
    ],
  },
  { "type": "error", "name": "FailedInnerCall", "inputs": [] },
  {
    "type": "error",
    "name": "TimelockInsufficientDelay",
    "inputs": [
      { "name": "delay", "type": "uint256", "internalType": "uint256" },
      { "name": "minDelay", "type": "uint256", "internalType": "uint256" },
    ],
  },
  {
    "type": "error",
    "name": "TimelockInvalidOperationLength",
    "inputs": [
      { "name": "targets", "type": "uint256", "internalType": "uint256" },
      { "name": "payloads", "type": "uint256", "internalType": "uint256" },
      { "name": "values", "type": "uint256", "internalType": "uint256" },
    ],
  },
  {
    "type": "error",
    "name": "TimelockUnauthorizedCaller",
    "inputs": [
      { "name": "caller", "type": "address", "internalType": "address" },
    ],
  },
  {
    "type": "error",
    "name": "TimelockUnexecutedPredecessor",
    "inputs": [
      {
        "name": "predecessorId",
        "type": "bytes32",
        "internalType": "bytes32",
      },
    ],
  },
  {
    "type": "error",
    "name": "TimelockUnexpectedOperationState",
    "inputs": [
      { "name": "operationId", "type": "bytes32", "internalType": "bytes32" },
      {
        "name": "expectedStates",
        "type": "bytes32",
        "internalType": "bytes32",
      },
    ],
  },
] as const;
