name: CI

on: [push]

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: stable

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "yarn"

      - name: Install dependencies
        run: yarn --frozen-lockfile --network-concurrency 1

      - name: Precompile using via-ir=true
        run: yarn build

      - name: Create env file
        run: |
          touch .env
          echo MAINNET_RPC="${{ vars.KNODE_URL }}/ethereum?key=${{ secrets.KNODE_API_KEY }}" >> .env
          echo SEPOLIA_RPC="${{ vars.KNODE_URL }}/sepolia?key=${{ secrets.KNODE_API_KEY }}" >> .env
          cat .env

      - name: Run tests
        shell: bash
        run: yarn test:unit

  integration-tests:
    name: Run Integration Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: stable

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "yarn"

      - name: Install dependencies
        run: yarn --frozen-lockfile --network-concurrency 1

      - name: Precompile via-ir=true
        run: yarn build

      - name: Create env file
        run: |
          touch .env
          echo MAINNET_RPC="${{ vars.KNODE_URL }}/ethereum?${{ secrets.KPK_TOKEN_CI_API_KEY }}" >> .env
          echo SEPOLIA_RPC="${{ vars.KNODE_URL }}/sepolia?${{ secrets.KPK_TOKEN_CI_API_KEY }}" >> .env
          cat .env

      - name: Run tests
        run: yarn test:integration

  lint:
    name: Lint Commit Messages
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: wagoid/commitlint-github-action@v5

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: stable

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "yarn"

      - name: Install dependencies
        run: yarn --frozen-lockfile --network-concurrency 1

      - run: yarn lint:check
